name: Deploy Rick and Morty

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
        cache-dependency-path: rick_and_morty/package-lock.json

    - name: Install dependencies
      working-directory: ./rick_and_morty
      run: npm ci

    - name: Build project
      working-directory: ./rick_and_morty
      run: |
        npm run build
        echo "=== Build folder structure ==="
        ls -R dist
        echo "=== File count ==="
        find dist -type f | wc -l

    - name: Upload Pages artifact
      id: upload-pages
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: rick_and_morty/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Download Pages artifact
      uses: actions/download-artifact@v4
      with:
        name: github-pages
        path: ./artifact

    - name: Inspect downloaded artifact
      run: |
        echo "=== Downloaded artifact contents ==="
        ls -R artifact
        echo "=== File count ==="
        find artifact -type f | wc -l

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
