name: CI and GitHub Pages Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: npm install --no-package-lock
      
    - name: Run tests
      run: npm test -- --watchAll=false --coverage
      
    - name: Build project
      run: npm run build
      
    - name: Verify production build
      run: |
        npm install -g serve
        serve -s dist -l 8080 &
        sleep 5
        curl http://localhost:8080

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: vite-build
        path: dist/

  deploy:
    needs: test-and-build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-build
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
